title: <p align="center"> Hồ Quốc Đạt </p>

logo: "/images/avatar.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="mailto:hahodat1958@gmail.com">Email</a> |
  <a href="https://github.com/QuocDatCoder">GitHub</a>
  </p>
  
  <p align="justify">
  I am a Software Engineering student at Sai Gon University (Expected Graduation: June 2026).
  <br><br>
  I have a strong passion for software development, full-stack web development, and academic research. I also enjoy building and customizing mechanical keyboards in my free time.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
